### ISSUE TITLE
price of a module

### ISSUE THREAD

**Issue by juliangruber** [libscie/business-plan#4]
> In order to get a module in the centralized registry, a small fee must be paid; 1EUR.

Have we discussed the various way of doing pricing? Pricing is hard to get right, often startups change their pricing model like 15x until they get it right.

My first thoughts reading the 1€ price are:

- will this make me write larger modules, to reduce cost?
- how expensive will a paper become?
- wouldn't it make more sense to pay a recurring fee so I can ensure the content will stay up forever?

Curious what you think @chartgerink @psobrakseaton!

**Comment by psobrakseaton** [comment]
This is something I was thinking about a few days ago. As Julian says, does pricing by the module encourage behavior that is contrary to what makes our system powerful? If we charge by module, would it encourage people to bundle modules with items that should be separate? My concern isn't for the fact that people won't be paying "the fair price", but that it undermines the integrity of networked modules.

I also second that a recurring fee makes sense in regards to maintenance.

Also, and granted this is coming from a place of financial privilege, while of the cost a EUR per module seems like it could quickly balloon, paying something like 5-15EUR a month to be able to centralize an "unlimited" amount of papers/modules seems like it could not only be more cost effective for the average researcher, but could perhaps provide better recurring revenue model for the company.

However, that could open us up to infrastructure abuse if institutions decide to centralize vast databases for next to no cost.

I know I am not adding much in the way of solutions, but I thought at least I would clue you into my headspace surrounding pricing.

**Comment by chartgerink** [comment]
I think that yes, it is possible people will post larger modules to keep costs down. I think that effect would interact with the price per module though, and if we would charge insane amounts I could imagine that being an issue. Is 1EUR an insane amount? I don't know. We should ask?

My personal thinking on this has been informed by the prices of publishing an article Open Access (i.e., Article Processing Charges). These are often around ~2000EUR but at least in the several hundred ([here is an example dataset from the Berlin Medical University](https://github.com/OpenAPC/openapc-de/blob/master/data/charite/2018_openapc_charite_utf-8.csv)). Based on that, I think 1EUR is reasonable enough, even if one research study would encompass 5-10 modules and you don't have to think about it subsequently.

If we would make it a subscription based fee, how would that work with archiving? If I need to pay to keep things available that relatively few people might be accessing, I will stop paying. In this situation, you need to keep thinking about it, which is an issue (I have anecdotal experience with Git LFS). We need to archive that long tail too. Does 1EUR cover the costs? Maybe not on an individual level, but the idea is that it would on average. This prediction might be wrong, and I think we could crunch the data once we get up and running to re-evaluate that pricing.

I agree subscriptions might be valuable, but not at the individual level. That would work at the institutional level, and that's part of the strategy :)

**Comment by juliangruber** [comment]
I guess this pricing model is just new to me and I'm coming from a SaaS background where I would expect something else (also for my own benefit). Registering a module to an author is effectively publishing it, right? So that step is fair to come at a small cost.

**Comment by chartgerink** [comment]
I think the discussion on `registration` v `publication` is important on that question :)

https://github.com/p2pcommons/specs/issues/19
