### ISSUE TITLE
Remove reference to real-world problems?

### ISSUE THREAD

**Issue by jameslibscie** [libscie/business-plan#7]
> I think we also want to enable science not relevant to real-world problems, or not-yet real-world problems

_Originally posted by @juliangruber in https://github.com/libscie/business-plan/pull/6/files_

**Comment by chartgerink** [comment]
My thoughts are that we want to enable any kind of science, and the demarcation between real-world problems and not is very flimsy anyway. 

In the end, we want to enable real-world scientists? 🍔

**Comment by jameslibscie** [comment]
I agree, so I'll remove this. The person who originally suggested this, mentioned it in the context of enabling discussion between scientists and practitioners to improve real-world application. Opening up participation and facilitating collaboration technically already covers this.
